spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/main-changelog.yaml

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Outbox
outbox.scheduler.enabled=true
outbox.scheduler.fixed-delay=5000
outbox.batch-size=10
outbox.max-retry-count=3

# X Payment API Configuration
xpayment.api.url=http://localhost:8080
xpayment.api.username=paymentAgentIprody
xpayment.api.password=iprodyTestPassword0123
xpayment.api.account-header=paymentAgentIprodyApiToken
xpayment.processing.delay-ms=60000