kafka.bootstrap.servers=localhost:9092

# Consumer Groups
kafka.consumer.payment.request.group=payment-request-group

# Kafka Topics
kafka.topic.payments.requests=payments.requests
kafka.topic.payments.response=payments.response
kafka.topic.payments.retry=payments.status.retry
kafka.topic.payments.dlq=payments.dlq

# Consumer Configuration
kafka.consumer.auto.offset.reset=earliest
kafka.consumer.enable.auto.commit=false

# Timeout Configurations
kafka.consumer.session.timeout.ms=45000
kafka.consumer.max.poll.interval.ms=300000
kafka.consumer.request.timeout.ms=65000

# Poll Configuration
kafka.consumer.max.poll.records=500
kafka.consumer.fetch.max.wait.ms=500

# Heartbeat Configuration
kafka.consumer.heartbeat.interval.ms=3000